config/routes.rb
Rails.application.routes.draw do
  # resources :users
  # resources :admins
  # # resource :login
  # resources :books
  # resources :products
  # resources :posts
  # resources :people
  # resources :clients do
  # root :to => 'students#show'
  # root "articles#index"
  # resources :students
  get '/students',to: "students#index"
  get 'students/:id',to: "students#show"

  #   get '/download_pdf', to: 'clients#download_pdf'
  #   # get '/login' , to: 'login#show'
  # end
  #  resources :login , only: [:show,:create]
  # GET /clients/1.pdf
  # get "/stream" , to: "my#stream"
  # get "/books" , to: "books#show"

  # get '/previews', to: 'comments#previews'
  # resources :comments do 
  #   get 'previews', on: :new
  # end


  # resources :photos
end

app/models/author.rb
class Author < ApplicationRecord
   has_many :books,->{order(year_published: :desc)}
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :supplier
  belongs_to :author

  has_many :reviews
  
  ## scopes
  scope :in_print, -> { where(out_of_print: false) }

  # default_scope { where(out_of_print: false) }
  scope :out_of_print, -> { where(out_of_print: true) }

  scope :recent, -> { where('year_published >= ?', Date.current.year - 50 )}
  scope :old, -> { where('year_published < ?', Date.current.year - 50 )}


  # scope :out_of_print, -> { where(out_of_print: true) }

  # def self.costs_more_than(amount)
  #   where("price > ?", amount)
  # end

end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  has_many :reviews
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  # scope :created_before, ->(time) { where("created_at < ?", time) if time.present? }
  enum :status, [:shipped, :being_packaged, :complete, :cancelled]

end

app/models/person.rb
class Person < ApplicationRecord
  has_one: age_detail
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/student.rb
class Student < ApplicationRecord
  validates :stu_name,presence: true
  validates :stu_surname,confirmation:true length: { is: 5 }, allow_blank: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new 
    @students = Student.new
  end

  def show
   @students = Student.find(params[:id])
   
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/my_helper.rb
module MyHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/index.html.erb
<table>
<tr>
<td>Stu_name</td>
<td>Stu_surname</td>
<td>Stu_age</td>

</tr>
<%= @students.each do |student| %>
<tr>
<td><%= student.stu_name %></td>
<td><%= student.stu_surname %></td>
<td><%= student.stu_age %></td>
<td><%#= link_to '/students', students_path(student) :method => :get%></td>

<td><%= link_to 'show',students_path(student), :method => :get%></td>
</tr>
<% end%>
</table>

app/views/students/new.html.erb
<%= form_for(@students) do |f| %>
  <%= f.label :stu_name %>
  <%= f.text_field :stu_name %>

  <%= f.label :stu_surname %>
  <%= f.text_field :stu_name %>

  <%= f.label :stu_age %>
  <%= f.text_field :stu_age%>

  <!--... -->
<% end %>

app/views/students/show.html.erb
<h1>Student Details</h1>
<br><br>
<h3>Student_Name:</h3><%= @students.stu_name %>
<h3>Student_surname:</h3><%= @students.stu_surname %>
<h3>Student_age:</h3><%= @students.stu_age %>

<a href ="/students"> Back</a>